name: CI/CD for apps

on:
  push:
    branches:
      - main

jobs:
  build-java-app:
    name: Build Java app
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    outputs:
      job_successful: ${{ steps.job_successful.outputs.job_successful }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check for changes in directory
        id: check_changes
        run: |
          if git diff-tree --name-only --no-commit-id ${{ github.sha }} | grep -q "^backend"; then
            echo "changes_made=yes" >> "$GITHUB_ENV"
          else
            echo "changes_made=no" >> "$GITHUB_ENV"
          fi
      - name: Set up QEMU
        if: ${{env.changes_made == 'yes'}}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64"
      - name: Set up Docker Buildx
        if: ${{env.changes_made == 'yes'}}
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Container Registry
        if: ${{env.changes_made == 'yes'}}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push the Docker image
        if: ${{env.changes_made == 'yes'}}
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "{{defaultContext}}:backend"
          platforms: "linux/arm64"
          tags: |
            indianbond/easystartup:suggest-feature-backend-latest-arm
            indianbond/easystartup:suggest-feature-backend-${{ github.sha }}-arm
      - id: job_successful
        if: ${{env.changes_made == 'yes'}}
        run: echo "job_successful=yes" >> "$GITHUB_OUTPUT"
  build-nextjs-app:
    name: Build NextJs app
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    outputs:
      job_successful: ${{ steps.job_successful.outputs.job_successful }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check for changes in directory
        id: check_changes
        run: |
          if git diff-tree --name-only --no-commit-id ${{ github.sha }} | grep -q "^frontend"; then
            echo "changes_made=yes" >> "$GITHUB_ENV"
          else
            echo "changes_made=no" >> "$GITHUB_ENV"
          fi
      - name: Set up QEMU
        if: ${{env.changes_made == 'yes'}}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64"
      - name: Set up Docker Buildx
        if: ${{env.changes_made == 'yes'}}
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Container Registry
        if: ${{env.changes_made == 'yes'}}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push the Docker image
        if: ${{env.changes_made == 'yes'}}
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:frontend"
          platforms: "linux/arm64"
          push: true
          tags: |
            indianbond/easystartup:suggest-feature-ui-latest-arm
            indianbond/easystartup:suggest-feature-ui-${{ github.sha }}-arm
      - id: job_successful
        if: ${{env.changes_made == 'yes'}}
        run: echo "job_successful=yes" >> "$GITHUB_OUTPUT"
  build-nextjs-portal:
    name: Build NextJs portal
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    outputs:
      job_successful: ${{ steps.job_successful.outputs.job_successful }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check for changes in directory
        id: check_changes
        run: |
          if git diff-tree --name-only --no-commit-id ${{ github.sha }} | grep -q "^frontend-portal"; then
            echo "changes_made=yes" >> "$GITHUB_ENV"
          else
            echo "changes_made=no" >> "$GITHUB_ENV"
          fi
      - name: Set up QEMU
        if: ${{env.changes_made == 'yes'}}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64"
      - name: Set up Docker Buildx
        if: ${{env.changes_made == 'yes'}}
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Container Registry
        if: ${{env.changes_made == 'yes'}}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push the Docker image
        if: ${{env.changes_made == 'yes'}}
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:frontend-portal"
          platforms: "linux/arm64"
          push: true
          tags: |
            indianbond/easystartup:suggest-feature-ui-portal-latest-arm
            indianbond/easystartup:suggest-feature-ui-portal-${{ github.sha }}-arm
      - id: job_successful
        if: ${{env.changes_made == 'yes'}}
        run: echo "job_successful=yes" >> "$GITHUB_OUTPUT"
  update-helm-repo-backend:
    needs: [build-java-app]
    name: Commit new revision in helm repo for java app
    if: ${{needs.build-java-app.outputs.job_successful == 'yes'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm repo
        uses: actions/checkout@v3
        with:
          repository: "easyStartup-pulse/helm-charts"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
      - name: Update backend values.yaml
        run: |
          cd charts/suggest-feature-backend/partition0
          sed -i 's|tag: "suggest-feature-backend-.*|tag: "suggest-feature-backend-'${{ github.sha }}'-arm"|' values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
  update-helm-repo-ui:
    needs: [build-nextjs-app]
    name: Commit new revision in helm repo for ui
    if: ${{needs.build-nextjs-app.outputs.job_successful == 'yes'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm repo
        uses: actions/checkout@v3
        with:
          repository: "easyStartup-pulse/helm-charts"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
      - name: Update values.yaml
        run: |
          cd charts/suggest-feature-ui
          sed -i 's|tag: "suggest-feature-ui-.*|tag: "suggest-feature-ui-'${{ github.sha }}'-arm"|' values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update ui values.yaml"
          git push
  update-helm-repo-ui-portal:
    needs: [build-nextjs-portal]
    name: Commit new revision in helm repo for frontend-portal
    if: ${{needs.build-nextjs-app.outputs.job_successful == 'yes'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm repo
        uses: actions/checkout@v3
        with:
          repository: "easyStartup-pulse/helm-charts"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
      - name: Update values.yaml
        run: |
          cd charts/suggest-feature-ui-portal
          sed -i 's|tag: "suggest-feature-ui-portal.*|tag: "suggest-feature-ui-portal-'${{ github.sha }}'-arm"|' values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update ui portal values.yaml"
          git push
